export const CANTEEN_CATEGORIES = [
  { id: 'all', name: 'Semua', icon: 'restaurant-outline' },
  { id: 'meals', name: 'Makanan', icon: 'nutrition-outline' },
  { id: 'snacks', name: 'Snack', icon: 'pizza-outline' },
  { id: 'drinks', name: 'Minuman', icon: 'cafe-outline' },
  { id: 'packages', name: 'Paket Hemat', icon: 'pricetag-outline' },
];

export const CANTEEN_PRODUCTS = [
  {
    id: 'prod_1',
    name: 'Nasi Goreng Telur Spesial',
    category: 'meals',
    stall: 'Kantin Mbok Darmi',
    price: 15000,
    rating: 4.9,
    ordersCount: 342,
    prepTime: '7 mnt',
    badge: 'Favorit',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=80',
    description: 'Nasi goreng bumbu gurih dengan telur dan kerupuk renyah.',
    isAvailable: true,
  },
  {
    id: 'prod_2',
    name: 'Mie Ayam Bakso Urat',
    category: 'meals',
    stall: 'Kantin Barokah',
    price: 14000,
    rating: 4.8,
    ordersCount: 280,
    prepTime: '5 mnt',
    badge: 'Terlaris',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=80',
    description: 'Mie kenyal dengan ayam kecap manis gurih dan 2 butir bakso.',
    isAvailable: true,
  },
  {
    id: 'prod_3',
    name: 'Dimsum Ayam Mentai (4 pcs)',
    category: 'snacks',
    stall: 'Pojok Dimsum',
    price: 12000,
    rating: 4.9,
    ordersCount: 195,
    prepTime: '4 mnt',
    badge: 'Populer',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500&auto=format&fit=crop&q=80',
    description: 'Dimsum ayam asli dengan topping saus mentai gurih lezat.',
    isAvailable: true,
  },
  {
    id: 'prod_4',
    name: 'Roti Bakar Keju Cokelat',
    category: 'snacks',
    stall: 'Kedai Santai',
    price: 10000,
    rating: 4.7,
    ordersCount: 150,
    prepTime: '6 mnt',
    badge: null,
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=500&auto=format&fit=crop&q=80',
    description: 'Roti tawar panggang isi keju parut dan krimer cokelat manis.',
    isAvailable: true,
  },
  {
    id: 'prod_5',
    name: 'Es Teh Manis Jasmine',
    category: 'drinks',
    stall: 'Depot Minuman',
    price: 4000,
    rating: 4.9,
    ordersCount: 520,
    prepTime: '2 mnt',
    badge: 'Best Seller',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=80',
    description: 'Es teh aroma melati segar porsi jumbo pelepas dahaga.',
    isAvailable: true,
  },
  {
    id: 'prod_6',
    name: 'Jus Alpukat Kental',
    category: 'drinks',
    stall: 'Depot Minuman',
    price: 10000,
    rating: 4.8,
    ordersCount: 110,
    prepTime: '4 mnt',
    badge: null,
    imageUrl: 'https://images.unsplash.com/photo-1638176066666-ffb2f5d0d619?w=500&auto=format&fit=crop&q=80',
    description: 'Jus alpukat buah asli kental manis dengan krimer cokelat.',
    isAvailable: true,
  },
  {
    id: 'prod_7',
    name: 'Paket KBM: Ayam Geprek + Es Teh',
    category: 'packages',
    stall: 'Kantin Mbok Darmi',
    price: 18000,
    rating: 5.0,
    ordersCount: 420,
    prepTime: '8 mnt',
    badge: 'Hemat',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&auto=format&fit=crop&q=80',
    description: 'Nasi ayam goreng crispy geprek pedas gurih plus es teh manis.',
    isAvailable: true,
  },
  {
    id: 'prod_8',
    name: 'Soto Ayam Lamongan',
    category: 'meals',
    stall: 'Kantin Bu Ani',
    price: 15000,
    rating: 4.8,
    ordersCount: 165,
    prepTime: '6 mnt',
    badge: null,
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=80',
    description: 'Soto ayam koya gurih hangat dengan suwiran ayam dan sayur.',
    isAvailable: true,
  },
];

export const INITIAL_WALLET_DATA = {
  balance: 0,
  formattedBalance: 'Rp 0',
  dailyLimit: 50000,
  formattedDailyLimit: 'Rp 50.000',
  spentToday: 0,
  formattedSpentToday: 'Rp 0',
  remainingDailyLimit: 50000,
  formattedRemainingLimit: 'Rp 50.000',
  cardNumber: '—',
  holderName: '',
  nisn: '',
  isBlocked: false,
  blockedReason: null,
  hasStudentPin: false,
  hasParentPin: false,
  qrCodeUrl: null,
};

export const INITIAL_TRANSACTIONS = [];
